title: View your Scene in top-down perspective
hero_image: images/banner.png
description: View your Scene in top-down perspective
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - 
    title: View your Scene in top-down perspective
